telemetry_host: ws://xxxxx:8000/feed
inactive_node_time: 10
subscribe:
  chains:
  - Polkadot
  - Kusama
polkadot:
  active_node_pattern: validator
  passive_node_pattern: passive
kusama:
  active_node_pattern: KUSAMAPROPHET
  passive_node_pattern: passive
